/**
 * Centralized help content registry.
 * Each entry answers: What is this? How is the data gathered? What is it useful for?
 */
export const HELP_CONTENT = {

  // ─── Page-level help ───────────────────────────────────────────

  'page.analytics': 'This page has moved. Visit Movement Intelligence for territory-aware metrics on care, presence, and narrative threads.',

  'page.intelligence': 'Movement Intelligence shows how care, relationships, and presence are unfolding across your territories. Data is aggregated from visits, events, reflections, provisions, and life events over the past 30 days. Metrics adapt to your organization archetype.',

  'page.journey': 'A visual board showing where each partnership is in its journey — from first discovery through sustained impact. Journey entries are auto-created when an opportunity reaches Discovery, and chapter changes are tracked automatically. Amber highlights indicate partnerships that may need a check-in (30+ days in chapter).',

  'page.anchors': 'Organizations that have reached first device distribution. Anchor records are created through the Journey conversion process to ensure lifecycle integrity. Volume, growth trend, and risk data are updated from fulfillment records.',

  'page.grants': 'Your funding pipeline from research through award. Track funder relationships, deadlines, amounts, and reporting schedules. Stage changes update automatically, and grants can be linked to specific metros and opportunities.',

  'page.events': 'Community outreach events and partner engagements. Track planning fields before and results after each event. When you mark an event as attended and write a reflection, that moment enters both the event record and the partnership story.',

  'page.command-center': 'Your daily starting point — context, not pressure. The Command Center adapts between Operational View (detail-dense planning) and Human Overview (story-first big picture). Data is assembled from your opportunities, pipeline, email suggestions, and community signals.',

  'page.reports': 'Build reports that tell the story of your work. The Impact View pulls live data from your partnerships, provisions, and community signals into narrative sections. Export as PDF for board meetings or schedule automatic delivery.',

  'page.metros': 'Geographic territories where your organization operates. Readiness scores are calculated from referral volume, staff coverage, partner counts, and anchor activity. Status levels (Expansion Ready, Anchor Build, Ecosystem Dev) reflect overall metro maturity.',

  'page.provisions': 'Technology request tracking from first request through delivery. Each provision moves through a delivery journey (Preparing → Ready → In Motion → On the Way → Delivered with Care). Communication threads keep fulfillment conversations in one place.',

  'page.intel-feed': 'A prioritized daily timeline of signals and connections. Items are generated by background processes (search, enrichment, watchlist, discovery) and ranked by signal strength, recency, and metro relevance. Check daily for the highest-impact outreach opportunities.',

  'page.momentum': 'A morale-positive U.S. visualization of metro-level activity. Scores use a time-decayed weighted model (Anchors 5×, Events 2×, Orders 1×) normalized against a 6-month baseline. Overlays show community signals, partner activity, and your reflections.',

  'page.metro-narratives': 'Living community stories blending external signals with your internal relationship data — reflections, momentum, and discovery highlights. The engine maintains a calm, reflective voice and never quotes your reflections directly.',

  'page.relationship-graph': 'A visual map of connections between organizations, people, grants, and events. Edges are built from shared contacts, linked grants, co-attended events, and campaign touches.',

  'page.settings': 'Configure your profile, appearance, AI integrations, notification preferences, and security settings. Gmail AI analysis, Read.ai webhooks, and push notifications are all managed here.',

  'page.discovery': 'Web search for prospecting. Queries are dispatched to an automation workflow, top URLs are micro-crawled for deeper extraction, and results are structured automatically. Saved searches can be re-run with deduplication.',

  'page.outreach': 'Build and send email campaigns directly from your connected Gmail. Audiences are built from opportunity filters and contact lists. Emails send in batches with rate limiting, failure categorization, and retry capability.',

  'page.automation-health': 'Workflow execution monitoring. Each automation run is tracked from dispatch through completion or failure. Use this to diagnose stuck workflows, review error messages, and verify callback integrity.',

  'page.feedback': 'Submit and track bug reports and feature requests. Your submissions are reviewed by the development team and updated with status changes.',

  // ─── Dashboard cards ───────────────────────────────────────────

  'card.kpi-active-anchors': 'Count of organizations currently producing device volume. Computed from anchor records with a first volume date. The sparkline shows 6-month trend.',

  'card.kpi-new-anchors': 'Anchors that reached first volume in the last 90 days. Tracks the pace of new partnership formation. Sparkline shows recent momentum.',

  'card.kpi-pipeline': 'Opportunities currently in the Journey (Discovery through Account Setup). Represents active partnerships being developed.',

  'card.kpi-median-days': 'Median time from first contact to first device volume across all anchors. A lower number means faster partnership formation.',

  'card.kpi-ramp': 'Anchors in the early production phase — producing volume but not yet at stable levels. These partnerships need attention and support.',

  'card.kpi-volume': 'Total devices distributed across all active anchors in the current month. Sparkline shows month-over-month trend.',

  'card.kpi-metro-coverage': 'Number of metros with at least one active anchor or pipeline opportunity.',

  'card.pipeline-chart': 'Visual breakdown of journey items by chapter. Each bar represents a chapter in the partnership journey. Data is pulled from journey records.',

  'card.anchor-trend': 'Historical view of anchor formation by month. Each data point represents new anchors reaching first volume that month. Useful for identifying seasonal patterns.',

  'card.stuck-pipeline': 'Partnerships that have been in the same chapter for 30+ days. These may need a check-in, a nudge, or a conversation about what\'s blocking progress.',

  'card.stale-next-steps': 'Partnerships whose next steps haven\'t been updated recently. Stale next steps suggest the relationship may be drifting — a good signal to reach out.',

  'card.recommendations': 'Strategic recommendations based on your journey data, community signals, and relationship patterns. Prioritized by predicted impact.',

  'card.metro-readiness': 'Readiness scores for each metro, calculated from anchor activity, demand signals, and operational capacity. Higher scores indicate readiness for expansion investment.',

  'card.top-anchors': 'Your highest-performing anchor partners ranked by volume, strategic value, and growth trend.',

  'card.overdue-actions': 'Actions past their due date across partnerships, journey items, and contact tasks. These need immediate attention.',

  'card.grant-kpis': 'Summary metrics for your grants — active grants, total value, requested and awarded amounts.',

  'card.discovery-briefing': 'Summaries from recent discovery research runs. Highlights new findings, suggested follow-ups, and community context relevant to your metros.',

  'card.relationship-ribbon': 'Your current focus partners — relationships that need attention based on recent activity, signals, or lack thereof. Click any card to jump to that opportunity.',

  'card.weekly-snapshot': 'A concise weekly summary of your activity, pipeline changes, and notable events. Refreshes each Monday.',

  'card.event-day-banner': 'Highlights events happening today or this week. Pulled from your events calendar so you never miss an engagement.',

  'card.local-pulse': 'Your Home Metro\'s weekly heartbeat. Every Monday, CROS discovers events and community happenings within 50 miles using RSS feeds, calendars, and web scraping.',

  // ─── Opportunity detail tabs ───────────────────────────────────

  'tab.the-partner': 'Who they are — organization knowledge, neighborhood insights, and mission alignment. Data comes from website bootstrapping, census records, and your manual enrichment.',

  'tab.the-story': 'How this partnership has grown. A blended timeline of reflections, emails, campaign touches, and event history — organized into natural story chapters. Privacy-safe: only extracted themes are shared, never raw text.',

  'tab.the-pulse': 'What\'s happening around them — watchlist signals, discovery results, and community context. Signals are generated from automated website monitoring and proactive research runs.',

  'tab.the-people': 'Relationships and contacts at this organization. Includes email history, meeting notes, tasks, and suggested contacts from your sent emails.',

  'tab.the-impact': 'What you\'ve done together — provisions delivered, grants linked, and reflections on shared work. Provision totals are computed from fulfillment records.',

  'tab.the-next-move': 'Gentle guidance for this partnership. Next Best Actions are scored by signal strength and predicted success. Outreach drafts use your company knowledge base for tone and approved claims.',

  // ─── Specific cards within opportunity detail ──────────────────

  'card.next-best-actions': 'Evidence-based recommended actions ranked by signal strength and predicted success. Generated from journey status, recent activity, community signals, and relationship momentum.',

  'card.outreach-drafts': 'Email drafts generated using your company knowledge base for tone, approved claims, and partner context. Review and customize before sending.',

  'card.outreach-suggestions': 'Campaign suggestions triggered by watchlist signals, event imports, or inactivity. Each includes a pre-filled template and human-readable reason.',

  'card.relationship-actions': 'Suggested relationship-building actions based on partnership stage, recent interactions, and community context.',

  'card.org-action-timeline': 'Chronological history of all actions taken for this partnership — activities, stage changes, outreach, and automated events.',

  'card.org-knowledge': 'Organization profile bootstrapped from their website. Includes mission, programs, leadership, and service areas.',

  'card.neighborhood-insights': 'Census and community context for the area where this partner operates. Includes demographics, economic indicators, and historical data.',

  'card.watchlist-signals': 'Recent website changes detected by automated monitoring. Signals are classified by type (hiring, expansion, funding, leadership change, program update).',

  // ─── Other specific cards ──────────────────────────────────────

  'card.suggested-outreach-feed': 'Follow-up suggestions based on: replies without follow-up (7d), watchlist signals without outreach (30d), and event imports without campaigns.',

  'card.suggested-actions-feed': 'Actionable suggestions surfaced from your email patterns, meeting commitments, and journey data.',

  'card.learning-dashboard': 'Track your progress with interactive tours and onboarding materials.',

  'card.email-suggestions': 'Suggestions extracted from your sent emails — new contacts, task commitments, and follow-up reminders. Each suggestion requires your approval before any action is taken.',

  'card.friday-scorecard': 'Weekly reflection summary available on Fridays. Reviews your activity, completed actions, and relationship progress for the week.',

  'card.leadership-brief': 'Executive-level summary of key metrics and notable changes. Designed for quick leadership check-ins.',

  'card.top-focus-items': 'Your highest-priority actions ranked by a weighted algorithm: overdue tasks (+40), grant deadlines (+35), high-probability journey items (+30), and relationship inactivity (+25). Data is assembled live from partnerships, journey records, grants, and activity history. Use this to decide where to spend your energy first each day.',

  'card.weekly-focus-plan': 'A weekly action plan created every Monday at 7 AM Central. Items are ranked by the same weighted scoring model and grouped by category. You can mark items complete, dismiss, or snooze them. Plans are owner-restricted and history is preserved for reflection.',

  'card.email-insights': 'Surfaces actionable intelligence from your connected Gmail. Sent emails from the last 24 hours are scanned for commitments, follow-ups, and new contacts. Results are grouped into bundles and presented as reviewable suggestions — nothing is created until you approve it. Only 280-character snippets are stored for privacy.',

  'card.anchor-velocity': 'A snapshot of anchor partnership momentum. Shows days since your last anchor conversion, how many are ramping up, and how many have reached stable scale. Data comes from anchor records and first-volume dates.',

  'card.story-signals': 'Gentle observations from NRI (Narrative Relational Intelligence). Story Signals surface connections, check-ins, and celebrations based on this week\'s relationship activity — never with urgency, always with care.',

  'card.recovery-breadcrumbs': 'When enabled, CROS keeps a short, private list of actions you take — like "deleted a contact" or "imported a file." This helps the assistant guide you through undo and restore. Breadcrumbs never include message content, names, notes, or private details. They are automatically removed after 30 days. You can turn this off at any time; the assistant will still help, but won\'t have context about recent actions.',

  'page.recovery': 'CROS has three layers of restoration. First, the Recycle Bin holds soft-deleted items for 90 days — you can restore them yourself. Second, action breadcrumbs (if enabled) let the assistant suggest what to undo. Third, Recovery Tickets let you request emergency help from a Gardener. Nothing is ever truly lost.',

  'page.garden-studio': 'Your safe editing workspace. Every change is audited, versioned, and reversible. Edit essays, playbooks, voice calibration, notifications, Communio directory, and feature switches — all draft-first, all with rollback.',

  'page.examen': 'A contemplative daily rhythm. The Morning Examen orients you through Noticing, Gratitude, Attention, and Invitation. The Evening Examen helps you close the day with reflection on where life moved, where resistance appeared, and what grew quietly. Each is shown once per calendar day.',

  'page.garden-pulse': 'A five-layer visual ecosystem view: Constellation (tenant nodes by Familia), Atlas (geographic metro presence), Timeline (chronological movement), Seasonal Rhythm (cyclical patterns), and Storybook (narrative highlights). Movement, not metrics.',

  'page.discovery-insights': 'Human-centric observations surfaced from anonymized behavioral signals. Insight cards highlight patterns of Discovery Interest and Adoption Friction — never technical errors. Maximum 3 per day, deduplicated, and framed in warm-professional language.',

  'page.financial-activity': 'A record of financial moments within your relationships. Generosity, participation, collaboration, and support — each recorded as part of the relational thread, not as transactions. Payments are handled securely through Stripe. Funds always go directly to your organization.',
} as const;

export type HelpKey = keyof typeof HELP_CONTENT;
