/**
 * CommunioGovernanceReview — Review and resolve governance flags for a Communio group.
 *
 * WHAT: Displays flagged governance issues (data boundary violations, sharing anomalies) with review actions.
 * WHERE: Communio page → Governance tab (visible to group creators / admins).
 * WHY: Governance flags need a human review workflow, not just database rows.
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Shield, CheckCircle2, AlertTriangle, XCircle, Clock } from 'lucide-react';
import { toast } from '@/components/ui/sonner';
import { format } from 'date-fns';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { HelpCircle } from 'lucide-react';

interface Props {
  groupIds: string[];
}

export function CommunioGovernanceReview({ groupIds }: Props) {
  const queryClient = useQueryClient();

  const { data: flags = [], isLoading } = useQuery({
    queryKey: ['communio-governance-flags', groupIds],
    queryFn: async () => {
      if (!groupIds.length) return [];
      const { data, error } = await supabase
        .from('communio_governance_flags')
        .select('*')
        .in('group_id', groupIds)
        .order('created_at', { ascending: false })
        .limit(50);
      if (error) throw error;
      return data || [];
    },
    enabled: groupIds.length > 0,
  });

  const resolveFlag = useMutation({
    mutationFn: async ({ flagId, action }: { flagId: string; action: 'reviewed' | 'dismissed' }) => {
      const { error } = await supabase
        .from('communio_governance_flags')
        .update({
          status: action,
          reviewed_at: new Date().toISOString(),
          reviewed_by: (await supabase.auth.getUser()).data.user?.id,
        })
        .eq('id', flagId);
      if (error) throw error;
    },
    onSuccess: (_, { action }) => {
      queryClient.invalidateQueries({ queryKey: ['communio-governance-flags'] });
      toast.success(action === 'reviewed' ? 'Flag reviewed and resolved' : 'Flag dismissed');
    },
  });

  const severityIcon = (severity: string) => {
    switch (severity) {
      case 'high': return <XCircle className="h-4 w-4 text-destructive" />;
      case 'medium': return <AlertTriangle className="h-4 w-4 text-amber-500" />;
      default: return <Shield className="h-4 w-4 text-muted-foreground" />;
    }
  };

  const severityBadge = (severity: string) => {
    switch (severity) {
      case 'high': return <Badge variant="destructive" className="text-xs">High</Badge>;
      case 'medium': return <Badge className="text-xs bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400">Medium</Badge>;
      default: return <Badge variant="outline" className="text-xs">Low</Badge>;
    }
  };

  const pendingFlags = flags.filter(f => f.status === 'open' || f.status === 'pending');
  const resolvedFlags = flags.filter(f => f.status === 'reviewed' || f.status === 'dismissed');

  if (isLoading) {
    return <p className="text-sm text-muted-foreground">Loading governance flags…</p>;
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <Shield className="h-5 w-5 text-primary" />
        <h3 className="font-semibold text-foreground">Governance Review</h3>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger>
              <HelpCircle className="h-4 w-4 text-muted-foreground" />
            </TooltipTrigger>
            <TooltipContent className="max-w-xs text-xs">
              <p><strong>What:</strong> Flags raised by the governance scanner for data sharing anomalies.</p>
              <p><strong>Where:</strong> Flags are auto-generated by the communio-governance-scan edge function.</p>
              <p><strong>Why:</strong> Ensures data boundaries are respected across organizational sharing.</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
        {pendingFlags.length > 0 && (
          <Badge variant="secondary" className="text-xs ml-auto">
            {pendingFlags.length} pending
          </Badge>
        )}
      </div>

      {/* Pending flags */}
      {pendingFlags.length === 0 && resolvedFlags.length === 0 && (
        <Card className="rounded-xl">
          <CardContent className="py-8 text-center">
            <CheckCircle2 className="h-6 w-6 mx-auto text-primary/40 mb-2" />
            <p className="text-sm text-muted-foreground font-serif">
              No governance flags. All sharing boundaries are clean.
            </p>
          </CardContent>
        </Card>
      )}

      {pendingFlags.map(flag => (
        <Card key={flag.id} className="rounded-xl border-l-4 border-l-amber-400">
          <CardContent className="p-4 space-y-3">
            <div className="flex items-start gap-3">
              {severityIcon(flag.severity)}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="font-medium text-sm text-foreground">
                    {flag.flag_type.replace(/_/g, ' ')}
                  </span>
                  {severityBadge(flag.severity)}
                </div>
                {flag.details && (
                  <p className="text-sm text-muted-foreground mt-1">{flag.details}</p>
                )}
                <p className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {format(new Date(flag.created_at), 'MMM d, yyyy h:mm a')}
                </p>
              </div>
            </div>
            <div className="flex gap-2 justify-end">
              <Button
                size="sm"
                variant="outline"
                onClick={() => resolveFlag.mutate({ flagId: flag.id, action: 'dismissed' })}
                disabled={resolveFlag.isPending}
              >
                Dismiss
              </Button>
              <Button
                size="sm"
                onClick={() => resolveFlag.mutate({ flagId: flag.id, action: 'reviewed' })}
                disabled={resolveFlag.isPending}
              >
                <CheckCircle2 className="h-4 w-4 mr-1" />
                Mark Reviewed
              </Button>
            </div>
          </CardContent>
        </Card>
      ))}

      {/* Resolved flags (collapsed) */}
      {resolvedFlags.length > 0 && (
        <details className="text-sm">
          <summary className="text-muted-foreground cursor-pointer hover:text-foreground transition-colors">
            {resolvedFlags.length} resolved flag{resolvedFlags.length !== 1 ? 's' : ''}
          </summary>
          <div className="space-y-2 mt-2">
            {resolvedFlags.slice(0, 10).map(flag => (
              <Card key={flag.id} className="rounded-xl opacity-60">
                <CardContent className="p-3 flex items-center gap-2">
                  <CheckCircle2 className="h-4 w-4 text-primary/50" />
                  <span className="text-sm">{flag.flag_type.replace(/_/g, ' ')}</span>
                  <Badge variant="outline" className="text-xs ml-auto">{flag.status}</Badge>
                  {flag.reviewed_at && (
                    <span className="text-xs text-muted-foreground">
                      {format(new Date(flag.reviewed_at), 'MMM d')}
                    </span>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </details>
      )}
    </div>
  );
}
