/**
 * CommunioProfileSetupWizard — Gentle opt-in wizard for public presence.
 *
 * WHAT: 3-step wizard to create/edit a Communio public profile with enrichment.
 * WHERE: /:tenantSlug/settings/communio-profile
 * WHY: Lets organizations share their presence with the network calmly.
 */
import { useState, useEffect, useCallback, useRef } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useTenant } from '@/contexts/TenantContext';
import { useTenantNavigate } from '@/hooks/useTenantPath';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { toast } from '@/components/ui/sonner';
import { Globe, Users, Eye, ArrowRight, ArrowLeft, Sparkles, Heart, Upload, FileText, X, Loader2 } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { HelpCircle } from 'lucide-react';

const AUTO_STORIES: Record<string, string> = {
  church: 'A faith community offering spiritual care, fellowship, and service to our neighbors.',
  digital_inclusion: 'An organization working to bridge the digital divide and ensure equitable access to technology.',
  social_enterprise: 'A purpose-driven enterprise creating social impact through sustainable business practices.',
  workforce_development: 'An organization dedicated to building pathways to meaningful employment for our community.',
  refugee_support: 'A welcoming community providing care, resources, and belonging for displaced families.',
  education_access: 'An organization opening doors to education and learning for those who need it most.',
  library_system: 'A community resource center offering knowledge, connection, and shared space for all.',
};

function generateAutoStory(archetype: string | null, orgName: string): string {
  if (archetype && AUTO_STORIES[archetype]) {
    return AUTO_STORIES[archetype];
  }
  return `${orgName} is a community-focused organization sharing its presence in the network.`;
}

export default function CommunioProfileSetupWizard() {
  const { tenant } = useTenant();
  const navigate = useTenantNavigate();
  const qc = useQueryClient();
  const tenantId = tenant?.id;

  const [step, setStep] = useState(1);
  const [orgName, setOrgName] = useState('');
  const [presenceStory, setPresenceStory] = useState('');
  const [websiteUrl, setWebsiteUrl] = useState('');
  const [contactEmail, setContactEmail] = useState('');
  const [networkVisible, setNetworkVisible] = useState(true);
  const [publicVisible, setPublicVisible] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Enrichment state
  const [enrichUrl, setEnrichUrl] = useState('');
  const [enrichPdf, setEnrichPdf] = useState<File | null>(null);
  const [isEnriching, setIsEnriching] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Load existing profile
  const { data: existing, isLoading } = useQuery({
    queryKey: ['communio-public-profile', tenantId],
    queryFn: async () => {
      if (!tenantId) return null;
      const { data } = await supabase
        .from('communio_public_profiles')
        .select('*')
        .eq('tenant_id', tenantId)
        .maybeSingle();
      return data as any;
    },
    enabled: !!tenantId,
  });

  // Prefill from tenant or existing profile
  useEffect(() => {
    if (existing) {
      setOrgName(existing.org_name || '');
      setPresenceStory(existing.presence_story || '');
      setWebsiteUrl(existing.website_url || '');
      setContactEmail(existing.contact_email || '');
      setNetworkVisible(existing.visibility === 'network' || existing.visibility === 'public');
      setPublicVisible(existing.visibility === 'public');
      setAutoGenerated(existing.auto_generated || false);
      setStep(2); // Skip invitation if already opted in
    } else if (tenant) {
      setOrgName(tenant.name || '');
    }
  }, [existing, tenant]);

  const visibility = publicVisible ? 'public' : networkVisible ? 'network' : 'private';

  // Enrichment handler
  const handleEnrich = useCallback(async () => {
    if (!tenantId) return;
    setIsEnriching(true);
    try {
      if (enrichPdf) {
        // Upload PDF then enrich
        const storagePath = `onboarding/${tenantId}/${crypto.randomUUID()}.pdf`;
        const { error: uploadErr } = await supabase.storage
          .from('kb-uploads')
          .upload(storagePath, enrichPdf, { contentType: 'application/pdf' });
        if (uploadErr) throw new Error(`Upload failed: ${uploadErr.message}`);

        const { data, error } = await supabase.functions.invoke('tenant-enrich-org', {
          body: { tenant_id: tenantId, pdf_storage_path: storagePath },
        });
        if (error) throw error;
        applyEnrichment(data);
      } else if (enrichUrl.trim()) {
        const { data, error } = await supabase.functions.invoke('tenant-enrich-org', {
          body: { tenant_id: tenantId, url: enrichUrl.trim() },
        });
        if (error) throw error;
        applyEnrichment(data);
      }
    } catch (err: any) {
      console.error('Enrichment error:', err);
      toast.error(err.message || 'Enrichment failed — you can fill in details manually.');
    } finally {
      setIsEnriching(false);
    }
  }, [tenantId, enrichUrl, enrichPdf]);

  const applyEnrichment = (data: any) => {
    const p = data?.profile;
    if (!p) {
      toast.info('No details could be extracted — you can fill them in manually.');
      return;
    }
    if (p.display_name && !orgName.trim()) setOrgName(p.display_name);
    if (p.mission_summary && !presenceStory.trim()) {
      setPresenceStory(p.mission_summary);
      setAutoGenerated(false);
    }
    if (p.city && p.state) {
      // Append location hint to story if not already present
    }
    toast.success('We learned a bit about your organization.');
  };

  const handlePdfSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (fileInputRef.current) fileInputRef.current.value = '';
    if (!file) return;
    if (file.type !== 'application/pdf') {
      toast.error('Only PDF files are supported.');
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      toast.error('Maximum file size is 5 MB.');
      return;
    }
    setEnrichPdf(file);
    setEnrichUrl('');
  }, []);

  const saveMutation = useMutation({
    mutationFn: async () => {
      if (!tenantId) throw new Error('No tenant');

      const storyToSave = presenceStory.trim() || generateAutoStory(tenant?.archetype ?? null, orgName);
      const isAuto = !presenceStory.trim();

      // Territory-aware: metros derived from tenant_territories on the server side
      const metros = tenant?.home_metro_id ? [tenant.home_metro_id] : [];

      const payload = {
        tenant_id: tenantId,
        org_name: orgName.trim(),
        archetype: tenant?.archetype ?? null,
        metros: JSON.stringify(metros),
        presence_story: storyToSave,
        website_url: websiteUrl.trim() || null,
        contact_email: contactEmail.trim() || null,
        visibility,
        auto_generated: isAuto,
      };

      if (existing) {
        const { error } = await supabase
          .from('communio_public_profiles')
          .update(payload as any)
          .eq('id', existing.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('communio_public_profiles')
          .insert(payload as any);
        if (error) throw error;
      }
    },
    onSuccess: async () => {
      if (visibility === 'public' || visibility === 'network') {
        try {
          await supabase.from('testimonium_events' as any).insert({
            tenant_id: tenantId,
            source_module: 'communio',
            event_kind: 'public_profile_published',
            summary: `${orgName.trim()} shared their presence in the network`.slice(0, 240),
            signal_weight: 3,
            metadata: { visibility, auto_generated: !presenceStory.trim() },
            occurred_at: new Date().toISOString(),
          });
        } catch (_) {
          // Silent
        }
      }

      toast.success('Your presence has been shared.');
      qc.invalidateQueries({ queryKey: ['communio-public-profile'] });
      navigate('/communio');
    },
    onError: (err: any) => {
      toast.error(err.message || 'Something went wrong');
    },
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <p className="text-sm text-muted-foreground">Loading…</p>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto p-4 md:p-6 space-y-6">
      {/* Header */}
      <div className="space-y-1">
        <div className="flex items-center gap-2">
          <h1 className="text-2xl font-bold tracking-tight">Communio Profile</h1>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger>
                <HelpCircle className="h-4 w-4 text-muted-foreground" />
              </TooltipTrigger>
              <TooltipContent className="max-w-xs">
                <p className="text-xs font-normal">
                  <strong>What:</strong> Your organization's presence in the Communio network.<br />
                  <strong>Where:</strong> Visible to other CROS organizations (and optionally publicly).<br />
                  <strong>Why:</strong> Help neighboring organizations discover your community presence.
                </p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <p className="text-muted-foreground text-sm">
          Share your presence with the network — gently, on your terms.
        </p>
      </div>

      {/* Step indicator */}
      <div className="flex items-center gap-2 text-xs text-muted-foreground">
        {[1, 2, 3].map(s => (
          <div
            key={s}
            className={`h-2 flex-1 rounded-full transition-colors ${
              s <= step ? 'bg-primary' : 'bg-muted'
            }`}
          />
        ))}
      </div>

      {/* Step 1: Invitation */}
      {step === 1 && (
        <Card className="rounded-xl">
          <CardContent className="py-12 text-center space-y-6">
            <div className="mx-auto w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
              <Heart className="h-8 w-8 text-primary" />
            </div>
            <div className="space-y-2 max-w-md mx-auto">
              <h2 className="text-xl font-semibold">Share your presence with the network</h2>
              <p className="text-sm text-muted-foreground font-serif leading-relaxed">
                The Communio directory helps neighboring organizations discover each other.
                No rankings, no metrics — just human presence.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <Button onClick={() => setStep(2)} className="gap-2">
                <Globe className="h-4 w-4" />
                Join the Network
                <ArrowRight className="h-4 w-4" />
              </Button>
              <Button variant="ghost" onClick={() => navigate('/settings')}>
                Not now
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Step 2: Presence Builder */}
      {step === 2 && (
        <Card className="rounded-xl">
          <CardHeader>
            <CardTitle className="text-lg">Your Presence</CardTitle>
            <CardDescription>Tell the network about your community presence — or let us learn from your website or a PDF.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            {/* ── Enrichment section ── */}
            {!existing && (
              <Card className="rounded-lg border-dashed">
                <CardContent className="p-4 space-y-3">
                  <p className="text-sm font-medium flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-primary" />
                    Auto-fill from your website or a document
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Paste your website or a public profile, or upload a PDF about your organization — we'll gently gather what we can to pre-fill your presence.
                  </p>

                  {/* URL input — hidden when PDF is selected */}
                  {!enrichPdf && (
                    <Input
                      value={enrichUrl}
                      onChange={e => setEnrichUrl(e.target.value)}
                      placeholder="https://yourchurch.org or https://facebook.com/yourministry"
                      className="text-sm"
                    />
                  )}

                  {/* Divider */}
                  {!enrichPdf && (
                    <div className="flex items-center gap-3">
                      <div className="flex-1 h-px bg-border" />
                      <span className="text-xs text-muted-foreground/60 uppercase tracking-wider">or</span>
                      <div className="flex-1 h-px bg-border" />
                    </div>
                  )}

                  {/* PDF upload */}
                  {enrichPdf ? (
                    <div className="flex items-center gap-3 p-3 rounded-lg border border-primary/20 bg-primary/5">
                      <FileText className="h-5 w-5 text-primary shrink-0" />
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium truncate">{enrichPdf.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {(enrichPdf.size / 1024).toFixed(0)} KB — ready for enrichment
                        </p>
                      </div>
                      <Button variant="ghost" size="icon" className="h-7 w-7 shrink-0" onClick={() => setEnrichPdf(null)}>
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  ) : (
                    <div className="relative">
                      <Button variant="outline" size="sm" className="w-full justify-start text-sm pointer-events-none">
                        <Upload className="h-4 w-4 mr-2 shrink-0" />
                        Upload a PDF about your organization
                      </Button>
                      <input
                        ref={fileInputRef}
                        type="file"
                        accept=".pdf,application/pdf"
                        onChange={handlePdfSelect}
                        className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                        style={{ fontSize: '0' }}
                      />
                    </div>
                  )}

                  <p className="text-xs text-muted-foreground/70">
                    Accepts websites, Facebook pages, LinkedIn profiles, Instagram bios, X/Twitter profiles, or PDFs (5 MB max).
                  </p>

                  <Button
                    size="sm"
                    variant="secondary"
                    disabled={isEnriching || (!enrichUrl.trim() && !enrichPdf)}
                    onClick={handleEnrich}
                    className="w-full"
                  >
                    {isEnriching ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin mr-2" />
                        Learning about your organization…
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4 mr-2" />
                        Auto-fill my presence
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>
            )}

            <div className="space-y-2">
              <Label htmlFor="org-name">Organization Name</Label>
              <Input
                id="org-name"
                value={orgName}
                onChange={e => setOrgName(e.target.value)}
                placeholder="Your organization"
              />
            </div>

            <div className="space-y-1">
              <Label className="text-muted-foreground text-xs">Archetype</Label>
              <p className="text-sm">{tenant?.archetype?.replace(/_/g, ' ') || 'Not set'}</p>
            </div>

            <div className="space-y-1">
              <Label className="text-muted-foreground text-xs">Metro</Label>
              <p className="text-sm">{tenant?.home_metro_id ? 'Linked' : 'Not set'}</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="presence-story">What kind of presence do you offer your city?</Label>
              <Textarea
                id="presence-story"
                value={presenceStory}
                onChange={e => { setPresenceStory(e.target.value); setAutoGenerated(false); }}
                placeholder={generateAutoStory(tenant?.archetype ?? null, orgName)}
                rows={4}
              />
              {!presenceStory.trim() && (
                <p className="text-xs text-muted-foreground flex items-center gap-1">
                  <Sparkles className="h-3 w-3" />
                  We'll write a gentle introduction for you if left blank.
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="website-url">Website (optional)</Label>
              <Input
                id="website-url"
                value={websiteUrl}
                onChange={e => setWebsiteUrl(e.target.value)}
                placeholder="https://…"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="contact-email">Contact email (optional)</Label>
              <Input
                id="contact-email"
                type="email"
                value={contactEmail}
                onChange={e => setContactEmail(e.target.value)}
                placeholder="hello@…"
              />
            </div>

            <div className="flex justify-between pt-2">
              <Button variant="ghost" onClick={() => setStep(1)}>
                <ArrowLeft className="h-4 w-4 mr-1" /> Back
              </Button>
              <Button onClick={() => setStep(3)} disabled={!orgName.trim()}>
                Continue <ArrowRight className="h-4 w-4 ml-1" />
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Step 3: Visibility */}
      {step === 3 && (
        <Card className="rounded-xl">
          <CardHeader>
            <CardTitle className="text-lg">Visibility</CardTitle>
            <CardDescription>Choose who can see your presence.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <div className="flex items-center gap-2">
                  <Users className="h-4 w-4 text-muted-foreground" />
                  <Label>Network visibility</Label>
                </div>
                <p className="text-xs text-muted-foreground">
                  Other CROS organizations in the directory can see your profile.
                </p>
              </div>
              <Switch checked={networkVisible} onCheckedChange={setNetworkVisible} />
            </div>

            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <div className="flex items-center gap-2">
                  <Eye className="h-4 w-4 text-muted-foreground" />
                  <Label>Public visibility</Label>
                </div>
                <p className="text-xs text-muted-foreground">
                  Anyone on the internet can see your profile page.
                </p>
              </div>
              <Switch checked={publicVisible} onCheckedChange={c => { setPublicVisible(c); if (c) setNetworkVisible(true); }} />
            </div>

            {/* Soft public mode hint */}
            {publicVisible && (
              <Card className="rounded-lg border-primary/20 bg-primary/5">
                <CardContent className="p-3 space-y-1">
                  <p className="text-xs font-medium flex items-center gap-1.5">
                    <Globe className="h-3.5 w-3.5" />
                    Use this as a simple public presence page
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Your profile will be available at <span className="font-mono text-foreground">/p/{tenant?.slug}</span> — a calm, shareable page for your organization.
                  </p>
                </CardContent>
              </Card>
            )}

            <div className="flex justify-between pt-2">
              <Button variant="ghost" onClick={() => setStep(2)}>
                <ArrowLeft className="h-4 w-4 mr-1" /> Back
              </Button>
              <Button
                onClick={() => saveMutation.mutate()}
                disabled={saveMutation.isPending || !orgName.trim()}
              >
                {saveMutation.isPending ? 'Saving…' : 'Share your presence'}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
