import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Loader2,
  Lightbulb,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Sparkles,
  AlertTriangle,
  TrendingUp,
  Shield,
  Check,
  X,
} from 'lucide-react';
import {
  useOrgInsights,
  useOrgActions,
  useGenerateOrgInsights,
  useExplainInsight,
  useUpdateActionStatus,
  useExecuteAction,
  type OrgInsight,
  type OrgRecommendedAction,
} from '@/hooks/useOrgInsights';
import { useActionOutcomes } from '@/hooks/useActionOutcomes';
import { DeepInsightBadge } from '@/components/ai/DeepInsightBadge';
import { ActionOutcomeFeedback } from './ActionOutcomeFeedback';
import { formatDistanceToNow } from 'date-fns';
import { useNavigate } from 'react-router-dom';

interface OrgInsightsPanelProps {
  orgId: string;
}

const SEVERITY_STYLES: Record<string, string> = {
  low: 'bg-info/15 text-info',
  medium: 'bg-warning/15 text-warning',
  high: 'bg-destructive/15 text-destructive',
};

const INSIGHT_ICONS: Record<string, typeof TrendingUp> = {
  momentum_increase: TrendingUp,
  community_need_alignment: Lightbulb,
  instability_risk: AlertTriangle,
};

function InsightCard({
  insight,
  actions,
}: {
  insight: OrgInsight;
  actions: OrgRecommendedAction[];
}) {
  const [expanded, setExpanded] = useState(false);
  const [showExplanation, setShowExplanation] = useState(false);
  const explainMutation = useExplainInsight();
  const updateAction = useUpdateActionStatus();
  const executeAction = useExecuteAction();
  const navigate = useNavigate();

  const Icon = INSIGHT_ICONS[insight.insight_type] || Lightbulb;

  const handleExplain = () => {
    if (insight.explanation) {
      setShowExplanation(!showExplanation);
      return;
    }
    explainMutation.mutate(
      { insightId: insight.id },
      {
        onSuccess: () => setShowExplanation(true),
      },
    );
  };

  const allInsightActions = actions.filter((a) => a.insight_id === insight.id);
  const insightActions = allInsightActions.filter((a) => a.status === 'open');
  const completedActions = allInsightActions.filter((a) => a.status !== 'open');
  const completedActionIds = completedActions.map((a) => a.id);
  const { data: outcomes } = useActionOutcomes(completedActionIds);
  const outcomesMap = new Map((outcomes || []).map((o) => [o.action_id, o]));

  return (
    <div className="border rounded-lg p-4 space-y-3">
      {/* Header */}
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-start gap-2 min-w-0">
          <Icon className="w-4 h-4 mt-0.5 text-primary shrink-0" />
          <div className="min-w-0">
            <p className="text-sm font-medium">{insight.title}</p>
            <div className="flex items-center gap-2 mt-1">
              <Badge className={`text-xs ${SEVERITY_STYLES[insight.severity]}`}>
                {insight.severity}
              </Badge>
              <span className="text-xs text-muted-foreground">
                {Math.round(insight.confidence * 100)}% confidence
              </span>
              <span className="text-xs text-muted-foreground">
                {formatDistanceToNow(new Date(insight.generated_at))} ago
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Summary */}
      <p className="text-sm text-muted-foreground">{insight.summary}</p>

      {/* Explain button */}
      <Button
        variant="ghost"
        size="sm"
        onClick={handleExplain}
        disabled={explainMutation.isPending}
        className="gap-1 text-xs"
      >
        {explainMutation.isPending ? (
          <Loader2 className="w-3 h-3 animate-spin" />
        ) : (
          <Sparkles className="w-3 h-3" />
        )}
        {insight.explanation ? (showExplanation ? 'Hide Explanation' : 'Show Explanation') : 'Explain'}
      </Button>

      {/* Explanation */}
      {showExplanation && insight.explanation && (
        <div className="bg-muted/30 rounded-lg p-3 text-sm whitespace-pre-line">
          {insight.explanation}
          {insight.explanation_model && (
            <p className="text-xs text-muted-foreground mt-2 italic">
              Generated by {insight.explanation_model}
            </p>
          )}
        </div>
      )}

      {/* Linked signals (expandable) */}
      {(insight.source as Record<string, unknown>)?.signal_ids && (
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setExpanded(!expanded)}
          className="gap-1 text-xs w-full justify-between"
        >
          <span>
            {((insight.source as Record<string, unknown>).signal_ids as string[])?.length || 0} linked signals
          </span>
          {expanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
        </Button>
      )}

      {expanded && (
        <div className="text-xs text-muted-foreground bg-muted/20 rounded p-2">
          Signal IDs: {((insight.source as Record<string, unknown>).signal_ids as string[])?.join(', ') || 'None'}
        </div>
      )}

      {/* Actions */}
      {insightActions.length > 0 && (
        <div className="space-y-2 pt-2 border-t">
          <p className="text-xs font-semibold text-muted-foreground uppercase">Recommended Actions</p>
          {insightActions.map((action) => (
            <div key={action.id} className="flex items-center justify-between gap-2 text-sm">
              <div className="min-w-0">
                <p className="font-medium text-sm">{action.title}</p>
                <p className="text-xs text-muted-foreground">{action.description}</p>
              </div>
              <div className="flex gap-1 shrink-0">
                <Button
                  size="sm"
                  variant="outline"
                  className="h-7 text-xs gap-1"
                  disabled={executeAction.isPending || updateAction.isPending}
                  onClick={() =>
                    executeAction.mutate(
                      { actionId: action.id },
                      {
                        onSuccess: (data) => {
                          if (data.navigate_to) {
                            navigate(data.navigate_to);
                          }
                        },
                      },
                    )
                  }
                >
                  {executeAction.isPending ? (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  ) : (
                    <Check className="w-3 h-3" />
                  )}
                  {action.cta_label}
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-7 text-xs"
                  disabled={updateAction.isPending}
                  onClick={() =>
                    updateAction.mutate({
                      actionId: action.id,
                      status: 'dismissed',
                      orgId: action.org_id,
                      actionType: action.action_type,
                    })
                  }
                >
                  <X className="w-3 h-3" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Completed actions with feedback */}
      {completedActions.length > 0 && (
        <div className="space-y-1 pt-2 border-t">
          <p className="text-xs font-semibold text-muted-foreground uppercase">Completed</p>
          {completedActions.map((action) => {
            const outcome = outcomesMap.get(action.id);
            return (
              <div key={action.id} className="flex items-center justify-between gap-2 text-sm">
                <p className="text-xs text-muted-foreground truncate">{action.title}</p>
                <ActionOutcomeFeedback
                  actionId={action.id}
                  orgId={action.org_id}
                  alreadyRecorded={!!outcome}
                  existingOutcome={outcome?.outcome_type}
                />
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

export function OrgInsightsPanel({ orgId }: OrgInsightsPanelProps) {
  const { data: insights, isLoading } = useOrgInsights(orgId);
  const insightIds = (insights || []).map((i) => i.id);
  const { data: actions } = useOrgActions(insightIds);
  const generateMutation = useGenerateOrgInsights();

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Shield className="w-4 h-4 text-primary" />
            Insights & Actions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="w-4 h-4 animate-spin" />
            Loading…
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <Shield className="w-4 h-4 text-primary" />
            Insights & Actions
          </CardTitle>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              className="gap-1"
              onClick={() => generateMutation.mutate({ orgId, force: false })}
              disabled={generateMutation.isPending}
            >
              {generateMutation.isPending ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <RefreshCw className="w-3.5 h-3.5" />
              )}
              Generate Insights
            </Button>
            <DeepInsightBadge />
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {!insights || insights.length === 0 ? (
          <div className="text-center py-6">
            <Lightbulb className="w-8 h-8 text-muted-foreground/50 mx-auto mb-2" />
            <p className="text-sm text-muted-foreground mb-3">
              No insights yet. Generate to detect momentum, alignment, and risks.
            </p>
            <Button
              size="sm"
              onClick={() => generateMutation.mutate({ orgId, force: false })}
              disabled={generateMutation.isPending}
            >
              {generateMutation.isPending ? (
                <><Loader2 className="w-4 h-4 mr-1 animate-spin" /> Analyzing…</>
              ) : (
                'Generate Insights'
              )}
            </Button>
          </div>
        ) : (
          <div className="space-y-3">
            {insights.map((insight) => (
              <InsightCard
                key={insight.id}
                insight={insight}
                actions={actions || []}
              />
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
