
-- Step 1: Update the 3 referenced old suites to map to real test files
UPDATE qa_test_suites SET name = 'Login Redirects After Auth', description = 'Verify login redirects to correct route after authentication', spec_path = 'qa-runner/tests/00_login_redirects_after_auth.spec.ts', updated_at = now() WHERE key = '00_smoke_login_dashboard';
UPDATE qa_test_suites SET name = 'Dashboard to Opportunities', description = 'Smoke test: navigate from dashboard to opportunities', spec_path = 'qa-runner/tests/01_smoke_dashboard_to_opportunities.spec.ts', updated_at = now() WHERE key = '01_nav_partners_opportunities';
UPDATE qa_test_suites SET name = 'Pricing Page Loads', description = 'Verify pricing page renders correctly', spec_path = 'qa-runner/tests/03_pricing_page_loads.spec.ts', updated_at = now() WHERE key = '03_nav_scheduling_calendar';

-- Step 2: Delete unreferenced old suites
DELETE FROM qa_test_suites WHERE key NOT IN ('00_smoke_login_dashboard', '01_nav_partners_opportunities', '03_nav_scheduling_calendar');

-- Step 3: Insert all actual test suites
INSERT INTO qa_test_suites (key, name, description, spec_path, enabled) VALUES
('02_sidebar_navigation_sweep', 'Sidebar Navigation Sweep', 'Verify all sidebar nav items are accessible', 'qa-runner/tests/02_sidebar_navigation_sweep.spec.ts', true),
('03_pricing_page_loads', 'Pricing Page Loads', 'Verify pricing page renders correctly', 'qa-runner/tests/03_pricing_page_loads.spec.ts', true),
('04_home_get_started_goes_to_pricing', 'Home Get Started → Pricing', 'CTA on home page navigates to pricing', 'qa-runner/tests/04_home_get_started_goes_to_pricing.spec.ts', true),
('05_pricing_to_stripe_redirect', 'Pricing → Stripe Redirect', 'Pricing plan click redirects to Stripe checkout', 'qa-runner/tests/05_pricing_to_stripe_redirect.spec.ts', true),
('06_login_invalid_credentials', 'Login Invalid Credentials', 'Verify error message on invalid credentials', 'qa-runner/tests/06_login_invalid_credentials.spec.ts', true),
('07_onboarding_wizard_smoke', 'Onboarding Wizard Smoke', 'Smoke test for onboarding wizard flow', 'qa-runner/tests/07_onboarding_wizard_smoke.spec.ts', true),
('08_settings_page_loads', 'Settings Page Loads', 'Verify settings page renders', 'qa-runner/tests/08_settings_page_loads.spec.ts', true),
('09_operator_console_admin_loads', 'Operator Console Loads', 'Verify operator console renders for admin', 'qa-runner/tests/09_operator_console_admin_loads.spec.ts', true),
('10_demo_lab_admin_loads', 'Demo Lab Loads', 'Verify demo lab renders for admin', 'qa-runner/tests/10_demo_lab_admin_loads.spec.ts', true),
('11_communio_page_loads', 'Communio Page Loads', 'Verify Communio page renders', 'qa-runner/tests/11_communio_page_loads.spec.ts', true),
('12_relatio_marketplace_loads', 'Relatio Marketplace Loads', 'Verify Relatio marketplace renders', 'qa-runner/tests/12_relatio_marketplace_loads.spec.ts', true),
('13_campaigns_addon_gating', 'Campaigns Addon Gating', 'Verify campaigns gated behind addon', 'qa-runner/tests/13_campaigns_addon_gating.spec.ts', true),
('14_unsubscribe_flow_smoke', 'Unsubscribe Flow Smoke', 'Verify unsubscribe flow works', 'qa-runner/tests/14_unsubscribe_flow_smoke.spec.ts', true),
('15_outlook_connect_ui_smoke', 'Outlook Connect UI Smoke', 'Verify Outlook connect UI renders', 'qa-runner/tests/15_outlook_connect_ui_smoke.spec.ts', true),
('16_open_first_opportunity', 'Open First Opportunity', 'Navigate to and open first opportunity detail', 'qa-runner/tests/16_open_first_opportunity.spec.ts', true),
('17_events_page_loads', 'Events Page Loads', 'Verify events page renders', 'qa-runner/tests/17_events_page_loads.spec.ts', true),
('18_provisions_page_loads', 'Prōvīsiō Page Loads', 'Verify provisions page renders', 'qa-runner/tests/18_provisions_page_loads.spec.ts', true),
('19_volunteers_page_loads', 'Voluntārium Page Loads', 'Verify volunteers page renders', 'qa-runner/tests/19_volunteers_page_loads.spec.ts', true),
('20_find_people_page_smoke', 'Find People Smoke', 'Verify find people page renders', 'qa-runner/tests/20_find_people_page_smoke.spec.ts', true),
('21_find_events_page_smoke', 'Find Events Smoke', 'Verify find events page renders', 'qa-runner/tests/21_find_events_page_smoke.spec.ts', true),
('22_find_grants_page_smoke', 'Find Grants Smoke', 'Verify find grants page renders', 'qa-runner/tests/22_find_grants_page_smoke.spec.ts', true),
('23_intel_feed_smoke', 'Intel Feed Smoke', 'Verify intel feed page renders', 'qa-runner/tests/23_intel_feed_smoke.spec.ts', true),
('24_logout_smoke', 'Logout Smoke', 'Verify logout flow works', 'qa-runner/tests/24_logout_smoke.spec.ts', true),
('25_visitor_role_voice_notes', 'Visitor Role Voice Notes', 'Verify visitor role can access voice notes', 'qa-runner/tests/25_visitor_role_voice_notes.spec.ts', true),
('26_create_opportunity', 'Create Opportunity', 'CRUD: create a new opportunity', 'qa-runner/tests/26_create_opportunity.spec.ts', true),
('27_edit_opportunity_detail', 'Edit Opportunity Detail', 'CRUD: edit opportunity details', 'qa-runner/tests/27_edit_opportunity_detail.spec.ts', true),
('28_people_page_crud', 'People Page CRUD', 'CRUD operations on people page', 'qa-runner/tests/28_people_page_crud.spec.ts', true),
('29_create_event', 'Create Event', 'CRUD: create a new event', 'qa-runner/tests/29_create_event.spec.ts', true),
('30_create_provision', 'Create Provision', 'CRUD: create a new provision', 'qa-runner/tests/30_create_provision.spec.ts', true),
('31_create_volunteer', 'Create Volunteer', 'CRUD: create a new volunteer', 'qa-runner/tests/31_create_volunteer.spec.ts', true),
('32_activities_page_crud', 'Activities Page CRUD', 'CRUD operations on activities', 'qa-runner/tests/32_activities_page_crud.spec.ts', true),
('33_grants_page_crud', 'Grants Page CRUD', 'CRUD operations on grants', 'qa-runner/tests/33_grants_page_crud.spec.ts', true),
('34_journey_reflection_flow', 'Journey Reflection Flow', 'Verify journey reflection creation flow', 'qa-runner/tests/34_journey_reflection_flow.spec.ts', true),
('35_testimonium_story_view', 'Testimonium Story View', 'Verify Testimonium story rendering', 'qa-runner/tests/35_testimonium_story_view.spec.ts', true),
('36_momentum_map_loads', 'Momentum Map Loads', 'Verify momentum map renders', 'qa-runner/tests/36_momentum_map_loads.spec.ts', true),
('37_pipeline_board_loads', 'Pipeline Board Loads', 'Verify pipeline board renders', 'qa-runner/tests/37_pipeline_board_loads.spec.ts', true),
('38_lens_shepherd_nav', 'Lens: Shepherd Nav', 'Verify shepherd role navigation', 'qa-runner/tests/38_lens_shepherd_nav.spec.ts', true),
('39_lens_companion_restricted', 'Lens: Companion Restricted', 'Verify companion role restrictions', 'qa-runner/tests/39_lens_companion_restricted.spec.ts', true),
('40_lens_visitor_redirects', 'Lens: Visitor Redirects', 'Verify visitor role redirect behavior', 'qa-runner/tests/40_lens_visitor_redirects.spec.ts', true),
('41_full_workspace_toggle', 'Full Workspace Toggle', 'Verify workspace toggle functionality', 'qa-runner/tests/41_full_workspace_toggle.spec.ts', true),
('41_visitor_lens_toggle', 'Visitor Lens Toggle', 'Verify visitor lens toggle for higher roles', 'qa-runner/tests/41_visitor_lens_toggle.spec.ts', true),
('42_onboarding_full_wizard', 'Onboarding Full Wizard', 'Full onboarding wizard end-to-end', 'qa-runner/tests/42_onboarding_full_wizard.spec.ts', true),
('43_unauthenticated_redirect', 'Unauthenticated Redirect', 'Verify unauthenticated users are redirected', 'qa-runner/tests/43_unauthenticated_redirect.spec.ts', true),
('44_settings_page_loads', 'Settings Page Loads (Extended)', 'Extended settings page verification', 'qa-runner/tests/44_settings_page_loads.spec.ts', true),
('45_calendar_page_loads', 'Calendar Page Loads', 'Verify calendar page renders', 'qa-runner/tests/45_calendar_page_loads.spec.ts', true),
('46_command_center_loads', 'Command Center Loads', 'Verify command center renders', 'qa-runner/tests/46_command_center_loads.spec.ts', true),
('47_metros_list_detail', 'Metros List & Detail', 'Verify metros list and detail pages', 'qa-runner/tests/47_metros_list_detail.spec.ts', true),
('48_anchors_page_loads', 'Anchors Page Loads', 'Verify anchors page renders', 'qa-runner/tests/48_anchors_page_loads.spec.ts', true),
('49_radar_page_loads', 'Radar Page Loads', 'Verify radar page renders', 'qa-runner/tests/49_radar_page_loads.spec.ts', true),
('50_narratives_page_loads', 'Narratives Page Loads', 'Verify narratives page renders', 'qa-runner/tests/50_narratives_page_loads.spec.ts', true),
('51_relationship_graph_loads', 'Relationship Graph Loads', 'Verify relationship graph renders', 'qa-runner/tests/51_relationship_graph_loads.spec.ts', true),
('52_help_page_loads', 'Help Page Loads', 'Verify help page renders', 'qa-runner/tests/52_help_page_loads.spec.ts', true),
('53_analytics_page_loads', 'Analytics Page Loads', 'Verify analytics page renders', 'qa-runner/tests/53_analytics_page_loads.spec.ts', true),
('54_reports_page_loads', 'Reports Page Loads', 'Verify reports page renders', 'qa-runner/tests/54_reports_page_loads.spec.ts', true),
('55_import_center_loads', 'Import Center Loads', 'Verify import center renders', 'qa-runner/tests/55_import_center_loads.spec.ts', true),
('56_signum_idle_prompt', 'Signum Idle Prompt', 'Verify Signum idle prompt telemetry', 'qa-runner/tests/56_signum_idle_prompt.spec.ts', true),
('57_signum_assist_chip', 'Signum Assist Chip', 'Verify Signum assist chip behavior', 'qa-runner/tests/57_signum_assist_chip.spec.ts', true),
('58_operator_signum_dashboard', 'Operator Signum Dashboard', 'Verify operator Signum dashboard', 'qa-runner/tests/58_operator_signum_dashboard.spec.ts', true),
('59_praeceptum_memory_update', 'Praeceptum Memory Update', 'Verify Praeceptum memory update flow', 'qa-runner/tests/59_praeceptum_memory_update.spec.ts', true),
('60_praeceptum_adaptive_prompt_order', 'Praeceptum Adaptive Prompt Order', 'Verify adaptive prompt ordering', 'qa-runner/tests/60_praeceptum_adaptive_prompt_order.spec.ts', true),
('61_operator_guidance_dashboard', 'Operator Guidance Dashboard', 'Verify operator guidance dashboard', 'qa-runner/tests/61_operator_guidance_dashboard.spec.ts', true),
('62_lumen_signal_detection', 'Lumen Signal Detection', 'Verify Lumen signal detection telemetry', 'qa-runner/tests/62_lumen_signal_detection.spec.ts', true),
('63_operator_lumen_dashboard', 'Operator Lumen Dashboard', 'Verify operator Lumen dashboard', 'qa-runner/tests/63_operator_lumen_dashboard.spec.ts', true),
('64_assistchip_lumen_prompt', 'AssistChip Lumen Prompt', 'Verify AssistChip Lumen prompt integration', 'qa-runner/tests/64_assistchip_lumen_prompt.spec.ts', true),
('65_stripe_checkout_boundary', 'Stripe Checkout Boundary', 'Verify Stripe checkout boundary behavior', 'qa-runner/tests/65_stripe_checkout_boundary.spec.ts', true)
ON CONFLICT (key) DO NOTHING;
