
-- ============================================
-- TESTIMONIUM CORE TABLES
-- ============================================

-- Reports generated by the story engine
CREATE TABLE public.testimonium_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  title text NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  scope jsonb NOT NULL DEFAULT '{}',
  narrative_json jsonb NOT NULL DEFAULT '{}',
  generated_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_testimonium_reports_tenant ON public.testimonium_reports(tenant_id, created_at DESC);

ALTER TABLE public.testimonium_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant members can view reports"
  ON public.testimonium_reports FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.tenant_users tu
    WHERE tu.tenant_id = testimonium_reports.tenant_id
      AND tu.user_id = auth.uid()
  ));

CREATE POLICY "Admin/leadership can insert reports"
  ON public.testimonium_reports FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.tenant_users tu
      WHERE tu.tenant_id = testimonium_reports.tenant_id
        AND tu.user_id = auth.uid()
    )
    AND public.has_any_role(auth.uid(), ARRAY['admin','leadership']::app_role[])
  );

CREATE POLICY "Admin/leadership can delete reports"
  ON public.testimonium_reports FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.tenant_users tu
      WHERE tu.tenant_id = testimonium_reports.tenant_id
        AND tu.user_id = auth.uid()
    )
    AND public.has_any_role(auth.uid(), ARRAY['admin','leadership']::app_role[])
  );

-- Report sections
CREATE TABLE public.testimonium_sections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES public.testimonium_reports(id) ON DELETE CASCADE,
  section_key text NOT NULL,
  order_index int NOT NULL,
  title text NOT NULL,
  content jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.testimonium_sections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant members can view sections"
  ON public.testimonium_sections FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.testimonium_reports r
    JOIN public.tenant_users tu ON tu.tenant_id = r.tenant_id AND tu.user_id = auth.uid()
    WHERE r.id = testimonium_sections.report_id
  ));

CREATE POLICY "Admin/leadership can insert sections"
  ON public.testimonium_sections FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.testimonium_reports r
    JOIN public.tenant_users tu ON tu.tenant_id = r.tenant_id AND tu.user_id = auth.uid()
    WHERE r.id = testimonium_sections.report_id
  ) AND public.has_any_role(auth.uid(), ARRAY['admin','leadership']::app_role[]));

-- Generation runs (tracking)
CREATE TABLE public.testimonium_generation_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'queued',
  period_start date,
  period_end date,
  stats jsonb DEFAULT '{}',
  error jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT valid_gen_status CHECK (status IN ('queued','running','complete','failed'))
);

CREATE INDEX idx_testimonium_gen_runs_tenant ON public.testimonium_generation_runs(tenant_id, created_at DESC);

ALTER TABLE public.testimonium_generation_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant members can view generation runs"
  ON public.testimonium_generation_runs FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.tenant_users tu
    WHERE tu.tenant_id = testimonium_generation_runs.tenant_id
      AND tu.user_id = auth.uid()
  ));

CREATE POLICY "Admin/leadership can manage generation runs"
  ON public.testimonium_generation_runs FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.tenant_users tu
      WHERE tu.tenant_id = testimonium_generation_runs.tenant_id
        AND tu.user_id = auth.uid()
    )
    AND public.has_any_role(auth.uid(), ARRAY['admin','leadership']::app_role[])
  );

-- ============================================
-- NRI SIGNALS TABLE
-- ============================================

CREATE TABLE public.nri_signals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  source text NOT NULL,
  signal_type text NOT NULL,
  signal_strength int NOT NULL DEFAULT 0,
  reference_id uuid NULL,
  occurred_at timestamptz NOT NULL,
  meta jsonb DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT valid_nri_source CHECK (source IN ('impulsus','signum','civitas','relatio','events','voluntarium'))
);

CREATE INDEX idx_nri_signals_tenant ON public.nri_signals(tenant_id, created_at DESC);
CREATE INDEX idx_nri_signals_source ON public.nri_signals(tenant_id, source, occurred_at DESC);

ALTER TABLE public.nri_signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant members can view NRI signals"
  ON public.nri_signals FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.tenant_users tu
    WHERE tu.tenant_id = nri_signals.tenant_id
      AND tu.user_id = auth.uid()
  ));

CREATE POLICY "Service can insert NRI signals"
  ON public.nri_signals FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.tenant_users tu
    WHERE tu.tenant_id = nri_signals.tenant_id
      AND tu.user_id = auth.uid()
  ));

-- Trigger for updated_at on testimonium_reports
CREATE TRIGGER update_testimonium_reports_updated_at
  BEFORE UPDATE ON public.testimonium_reports
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();
