
-- Relationship Story Suggestions: gentle, narrative-driven prompts
-- Generated by metro-narrative-build, surfaced in Story UI only
CREATE TABLE public.relationship_story_suggestions (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  opportunity_id uuid NOT NULL REFERENCES public.opportunities(id) ON DELETE CASCADE,
  metro_id uuid NOT NULL REFERENCES public.metros(id) ON DELETE CASCADE,
  suggestion_type text NOT NULL CHECK (suggestion_type IN ('check_in', 'event_connect', 'reflection_prompt')),
  summary text NOT NULL,
  source_context jsonb NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'acted', 'dismissed')),
  acted_at timestamptz NULL,
  dismissed_at timestamptz NULL,
  run_id text NULL,
  inputs_hash text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX idx_rss_metro_status ON public.relationship_story_suggestions (metro_id, status, created_at DESC);
CREATE INDEX idx_rss_opportunity ON public.relationship_story_suggestions (opportunity_id, created_at DESC);

-- Idempotency: prevent duplicate suggestions per opportunity+type+hash
CREATE UNIQUE INDEX idx_rss_dedup ON public.relationship_story_suggestions (opportunity_id, suggestion_type, inputs_hash) WHERE inputs_hash IS NOT NULL;

-- RLS
ALTER TABLE public.relationship_story_suggestions ENABLE ROW LEVEL SECURITY;

-- Read: users with metro access
CREATE POLICY "Users with metro access can read suggestions"
  ON public.relationship_story_suggestions
  FOR SELECT
  USING (public.has_metro_access(auth.uid(), metro_id));

-- Update (act/dismiss): users with metro access
CREATE POLICY "Users with metro access can update suggestions"
  ON public.relationship_story_suggestions
  FOR UPDATE
  USING (public.has_metro_access(auth.uid(), metro_id));

-- Insert: service-role only (no policy = deny for regular users)

-- Updated_at trigger
CREATE TRIGGER set_rss_updated_at
  BEFORE UPDATE ON public.relationship_story_suggestions
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();
